update to correctly handle errors and fetch directly to master

diff --git a/.github/workflows/finalize-release.yaml b/.github/workflows/finalize-release.yaml
--- a/.github/workflows/finalize-release.yaml
+++ b/.github/workflows/finalize-release.yaml
@@ -17,14 +17,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - run: echo test
+        with:
+          ref: master
+          fetch-depth: 0
       - name: Set Git Config
         run: |
           git config --local user.email 38288322+imodeljs-admin@users.noreply.github.com
           git config --local user.name imodeljs-admin
-
-      - name: Switch to master
-        run: git checkout --track origin/master
       - name: Cherry-pick changelogs
         run: |
           git cherry-pick $commitid
@@ -40,14 +39,23 @@ jobs:
           git add **/package.json **/version-policies.json common/changes docs/changehistory/NextVersion.md
 
           commitMessage=$(git log --format=%B -n 1 $commitid)
-
-          # Git commit should fail if there are outstanding conflicts
           git commit -m "$commitMessage Changelogs"
+
+          exitCode=$?
+          if [ $exitCode -ne 0 ]
+          then
+            echo Failed to cherry-pick changelogs for $commitMessage. Commit id is $commitid
+            exit $exitCode
+          fi
 
           rush change --bulk --message "" --bump-type none
           git add .
           git commit --amend --no-edit
+
+          exit $?
         env:
           commitid: ${{ github.sha }}
+        # turn off the default behavior to fail fast. The script has its own error handling
+        shell: bash {0}
       - name: Push to master
         run: git push https://$(GITHUBTOKEN)@github.com/imodeljs/imodeljs HEAD:master
